### Admin can use the same endpoints as the client and also extra endpoints
@host = http://localhost:3000
@tokenAdmin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjF9.RfopwvQBbCp4QP3VGyYMR6CcjBKBlbhf2aIFIZFCLmU

### Admin endpoints

### Get all users
GET {{host}}/api/admin/user?page=2&limit=2&order=desc
Authorization: {{tokenAdmin}}

### Get user by id
GET {{host}}/api/admin/user/39
Authorization: {{tokenAdmin}}

### Update user by id
PUT {{host}}/api/admin/user/39
Authorization: {{tokenAdmin}}
Content-Type: application/json

{
    "name": "Cabezon Admin",
    "role": "admin"
}

### Delete user by id
DELETE {{host}}/api/admin/user/39
Authorization: {{tokenAdmin}}
