@host = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiY2xpZW50In0.hxOv1OBToXPH8ObHlGjl-4S1S62rCIz2XRZeisZ4zyo
@tokenAdmin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjEsInJvbGUiOiJhZG1pbiJ9.OpkP666aKDaMEhwdcpLEVnc77A9xZfBHQMMUsUAzC5I

### Register a new user
POST {{host}}/api/user
Content-Type: application/json

{
    "name": "Joel Ricardo",
    "surname": "Reyes Cruz",
    "phone": "637398857",
    "password": "12345",
    "email": "joelricardo.rc@gmail.com"  
}

### Login a user
POST {{host}}/api/user/login
Content-Type: application/json

{
    "email": "andry.html@gmail.com",
    "password": "12345"
}

### Get a user
GET {{host}}/api/user/21
Authorization: {{token}}

### Get all users
GET {{host}}/api/user?page=1&limit=2&order=desc
Authorization: {{tokenAdmin}}

### Update a user
PUT {{host}}/api/user
Content-Type: application/json
Authorization: {{token}}

{
    "name": "Alexis1",
    "surname": "Reyes",
    "phone": "1234567890"
}

### Delete a user
DELETE {{host}}/api/user
Authorization: {{token}}
