@host = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzE2NzM1MzV9.5jxz7gSvLmpOQ3p-ZHT769ZEmgUOtCWmRU-1LH9Y35M

### Get all users   
GET {{host}}/api/users

### Register a new user
POST {{host}}/api/user/register
Content-Type: application/json

{
    "name": "Alexis",
    "surname": "Reyes",
    "phone": "1234567890",
    "password": "12345",
    "email": "alexis@gmail.com",
    "role": "admin"
}

### // Get a menu with ID
GET {{host}}/api/menus/id 

### // Get all menus
GET {{host}}/api/menus

###
POST {{host}}/api/menus
Content-Type: application/json

{
    "id": 4,
    "date": "2024-11-18"
}
### Login a user
POST {{host}}/api/user/login
Content-Type: application/json

{
    "email": "alexis@gmail.com",
    "password": "12345"
}

### Get all users   
POST {{host}}/api/users/menu
# Authorization: Bearer {{token}}
