@host = http://localhost:3000

### // Get a menu with ID
GET {{host}}/api/menus/id 

### // Get all menus
GET {{host}}/api/menus

###
POST {{host}}/api/menus
Content-Type: application/json

{
    "date": "2024-11-18"
}