@host = http://localhost:3000

### // Get a menu with ID
GET {{host}}/api/menus/18

### // Get all menus
GET {{host}}/api/menus

###
POST {{host}}/api/menus
Content-Type: application/json

{
    "dishes":[
        1, 5, 15
        
    ], 
    "date": "2024-11-19",
    "name": "menu lunes"
    }
