//@host = http://localhost:3000
@host = https://crm-restaurant.onrender.com
### Get all
GET {{host}}/api/reservations

### Get all with optional params
GET {{host}}/api/reservations?date=2024-11-19&user_id=1&status=pending

### Get all customers reservations with optional params
GET {{host}}/api/reservations/customer?date=2024-11-25

### Get by id
GET {{host}}/api/reservations/1

### POST a reservation (with tables)
POST {{host}}/api/reservations
Content-Type: application/json

{
    "date": "2025-08-18",
    "time": "breakfast",
    "guests": 1,
    "status": "pending",
    "user_id": 1,
    "location": "inside"
}

### Delete by id
DELETE {{host}}/api/reservations/SSAD

### Update status by id 
PUT {{host}}/api/reservations/1/status/confirmed

#################### TABLES ####################

### Get all
GET {{host}}/api/tables

### Get available tables
GET {{host}}/api/tables/available/2024-04-01
