@host = https://crm-restaurant.onrender.com
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjF9.8V1LvGZLMR7N44EcVTGxJ7PYn2zJMeZ77YMFOx2QY3g

### Reviews endpoints

### Create a review
POST {{host}}/api/review
Authorization: {{token}}
Content-Type: application/json

{
    "rating": 5,
    "comment": "ME CAGO EN LA PUTA 2"
}

### Get all user reviews
GET {{host}}/api/review
Authorization: {{token}}

### Delete a review
DELETE {{host}}/api/review/2
Authorization: {{token}}


### Get all reviews
GET {{host}}/api/review/all
