@host = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ODJ9.WG3WN6l1l36pUej9ZCjavqJcjOWDvkL0p8LsOtenoiE

### Reviews endpoints

### Create a review
POST {{host}}/api/review
Authorization: {{token}}
Content-Type: application/json

{
    "rating": 5,
    "comment": "ME CAGO EN LA PUTA 2"
}

### Get all user reviews
GET {{host}}/api/review
Authorization: {{token}}

### Delete a review
DELETE {{host}}/api/review/2
Authorization: {{token}}
