@host = https://crm-restaurant.onrender.com
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTR9.O_I9pZmtxJxSGuXXIAMqsbBQDwmUcZNWSuK1sded9Lw

### Client endpoints

### Get user profile
GET {{host}}/api/user
Authorization: {{token}}

### Register user
POST {{host}}/api/user
Content-Type: application/json

{
    "name": "Andry",
    "surname": "Reyes",
    "phone": "637398857",
    "password": "12345678",
    "email": "andry.html@gmail.com"
}

### Login user
POST {{host}}/api/user/login
Content-Type: application/json

{
    "email": "andry.html@gmail.com",
    "password": "12345678"
}

### Update a user
PUT {{host}}/api/user
Content-Type: application/json
Authorization: {{token}}

{
    "name": "Alma Joel",
    "surname": "Reyes Garcia",
    "phone": "637398857",
    "email": "alma@gmail.com",
    "password": "12345"
}

### Delete a user
DELETE {{host}}/api/user
Authorization: {{token}}