@host = https://crm-restaurant.onrender.com
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDB9.W4aqvh53FH9sBstAn6kDt0FOf4WIMWemFIpmaavsOus

### Client endpoints

### Get user profile
GET {{host}}/api/user
Authorization: {{token}}

### Register user
POST {{host}}/api/user
Content-Type: application/json

{
    "name": "Noe",
    "surname": "Mesa",
    "phone": "637398857",
    "password": "12345",
    "email": "noe@gmail.com"  
}

### Login user
POST {{host}}/api/user/login
Content-Type: application/json

{
    "email": "andry.html@gmail.com",
    "password": "12345"
}

### Update a user
PUT {{host}}/api/user
Content-Type: application/json
Authorization: {{token}}

{
    "name": "Alma Joel",
    "surname": "Reyes Garcia",
    "phone": "637398857",
    "email": "alma@gmail.com",
    "password": "12345"
}

### Delete a user
DELETE {{host}}/api/user
Authorization: {{token}}